version: "3.9"
services:
  web:
    build: .
    #image: daarling/yourhometel
    ports:
      - "8444:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/yourHOmeTEL?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=change_me
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=yourhometel
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql