version: "3.9"
services:
  web:  
    image: daarling/yourhometel
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/yourhometel
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=change_me
    depends_on:
      - db
    restart: on-failure

  db:
#    container_name: db
    image: mysql:8.0.22
    restart: always
    ports:
    - "3307:3306"
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=yourhometel
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql:/var/lib/mysql
      #- ./my.cnf:/etc/mysql/my.cnf
volumes:
  mysql: